version: 1.0
Resources:
  - TargetService:
      Type: AWS::ECS::Service
      Properties:
        TaskDefinition: "arn:aws:ecs:ap-south-1:278105647443:task-definition/order-service-codebuild:1"
        LoadBalancerInfo:
          ContainerName: "order-service-container"
          ContainerPort: "80"
        PlatformVersion: "LATEST"
        